### ISSUE TITLE
consider word senses similarity in lexrank

### ISSUE THREAD

**Issue by melonskin** [mekomlusa/aston#17]
use [synset1.wup_similarity()](http://www.nltk.org/howto/wordnet.html) to get a score. Thinking about how to include it in lexrank formula.

**Comment by mekomlusa** [comment]
Good idea. Didn't know that nltk has this functionality. Will try this on netsum.

**Comment by mekomlusa** [comment]
Or we can try the simple ones: Jaccard/cosine similarity. https://towardsdatascience.com/overview-of-text-similarity-metrics-3397c4601f50
The problem would be - these metrics DO NOT measure semantic similarity. So they will say "This is a tree" and "This is not a tree" are similar. This might be something we would like to consider. For semantic similarity, a quick search online seems to suggest that we can use word2Vec/doc2Vec, but then we will have to use the 90k documents to train the model. Not sure if this worths the time.
Any ideas?

**Comment by melonskin** [comment]
1. Seems Jaccard/cosine similarity measures similarities of two sentences. We are using cosine one right now for lexrank.
2. For news, one mainly express a single idea. "This is a tree" and "This is not a tree" may not appear in the same new example.
3. word2vec is a good idea, not quite familiar with it. But currently, I am identifying which part causes the slow execution
  - calculate every pair of words, increase the run time to $n^2$
  - or a single similarity func call is time consuming

**Comment by mekomlusa** [comment]
Looks like Jaccard similarity is somehow being covered in netsum already. Will try to add the similarity measure from NLTK, but if it's significantly slower will try something else.

**Comment by mekomlusa** [comment]
Should we consider using other WordNet-based similarity metrics? Path seems to be fine, but the wordnet interface does offer more (LCS, Lin etc).
