### ISSUE TITLE
Python dictionary count improvement suggestion

### ISSUE THREAD

**Issue by mekomlusa** [mekomlusa/aston#23]
https://github.com/mekomlusa/aston/blob/79acee2ef3793f80f26c8355ca6df34887948805/codes/extractive/lex_rank/lex_rank.py#L99

Seems like this line is trying to update word count in a dictionary. Just a minor suggestion, the below syntax also works: (I actually prefer to write in this way)
`w_count_1[w] = w_count_1.get(w,0) + 1`
Or you may consider using `Counter` from the `Collections` class - even more [neat](https://stackoverflow.com/a/20511316).

**Comment by melonskin** [comment]
Good to know! Thanks dalao.
