### ISSUE TITLE
test data set not work

### ISSUE THREAD

**Issue by chenshaw1995** [mekomlusa/aston#27]
I am trying to test lsa on data provided in datalist_2K_tesing.csv, summary_samples, and text_samples, but a lot of files in datalist.csv could not be found in summary_samples or text_samples. Am I using the wrong dataset? Could anyone provide the latest completed test dataset for me? Thanks!

**Comment by mekomlusa** [comment]
I will upload the processed 90k samples to the shared drive. These samples do not belong to the original 20K shared.
